vich_uploader:
    db_driver: orm

    mappings:
        glossaries:
            uri_prefix: /images/glossaries
            upload_destination: '%kernel.project_dir%/public/images/glossaries'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        seas:
            uri_prefix: /images/seas
            upload_destination: '%kernel.project_dir%/public/images/seas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 